#!/usr/bin/env python3
"""Full 0TH2.BIN Lossless Assembly Container Generator.

Mechanically generates:
1. Private assembly container (.private/asm/0TH2/0TH2.s) with proven code
   emitted as real SH-2 mnemonics and RAW_UNKNOWN emitted as .byte directives.
2. Linker script (asm/linker/0TH2.ld) asserting VMA 0x06004000 and 535552 bytes.
3. Provenance manifest (asm/manifests/0TH2.BIN.json).
"""

from typing import Any, Dict, List, Set, Tuple
import argparse
import hashlib
import json
import os
import subprocess
import sys

MODULE_NAME = "0TH2.BIN"
MODULE_VMA = 0x06004000
MODULE_SIZE = 535552
CANONICAL_MODULE_SHA = "c1cc4117870bc567386410aa2d4f1b5f03fb98a601be71bb3ae2155de1853c64"
DISC_BIN_PATH = "The_Story_of_Thor_2_[RUS]_(NTSC).bin"


def extract_canonical_module(repo_root: str) -> bytes:
    """Extract canonical 0TH2.BIN from disc image."""
    disc_path = os.path.join(repo_root, DISC_BIN_PATH)
    if not os.path.exists(disc_path):
        raise FileNotFoundError(f"Disc image not found: {disc_path}")
    lba = 24
    data = bytearray()
    with open(disc_path, "rb") as f:
        f.seek(lba * 2352)
        while len(data) < MODULE_SIZE:
            sec = f.read(2352)
            if not sec:
                break
            data.extend(sec[16:16 + 2048])
    module_bytes = bytes(data[:MODULE_SIZE])
    if len(module_bytes) != MODULE_SIZE:
        raise ValueError(f"Extracted size mismatch: {len(module_bytes)} != {MODULE_SIZE}")
    actual_sha = hashlib.sha256(module_bytes).hexdigest()
    if actual_sha != CANONICAL_MODULE_SHA:
        raise ValueError(f"Module SHA mismatch: {actual_sha} != {CANONICAL_MODULE_SHA}")
    return module_bytes


def run_cpp_ir_exporter(repo_root: str, module_bin_path: str, ir_out_path: str) -> Dict[str, Any]:
    """Execute C++ export_sh2_asm_ir tool to obtain Thor-decoder-backed IR."""
    exe_name = "export_sh2_asm_ir.exe" if sys.platform == "win32" else "export_sh2_asm_ir"
    exe_path = os.path.join(repo_root, "build", exe_name)
    if not os.path.exists(exe_path):
        # Try finding in root or path
        exe_path = os.path.join(repo_root, exe_name)
        if not os.path.exists(exe_path):
            raise FileNotFoundError(f"IR exporter executable not found: {exe_path}")

    os.makedirs(os.path.dirname(os.path.abspath(ir_out_path)), exist_ok=True)
    cmd = [
        exe_path,
        os.path.abspath(module_bin_path),
        f"0x{MODULE_VMA:08X}",
        os.path.abspath(ir_out_path),
        "0x06004000:0x0600400C:bb_06004000",
        "0x06004280:0x0600428A:bb_06004280",
    ]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        raise RuntimeError(f"C++ IR exporter failed:\n{res.stderr}\n{res.stdout}")

    with open(ir_out_path, "r", encoding="utf-8") as f:
        return json.load(f)


def generate_assembly(
    module_bytes: bytes,
    ir_data: Dict[str, Any],
    out_s_path: str,
) -> None:
    """Generate private lossless assembly file."""
    os.makedirs(os.path.dirname(os.path.abspath(out_s_path)), exist_ok=True)

    labels_by_offset: Dict[int, List[str]] = {}
    for l in ir_data.get("labels", []):
        offset = l["offset"]
        labels_by_offset.setdefault(offset, []).append(l["name"])

    # Add block labels
    labels_by_offset.setdefault(0, []).append("bb_06004000")
    labels_by_offset.setdefault(0x280, []).append("bb_06004280")

    blocks_by_offset: Dict[int, Dict[str, Any]] = {}
    for b in ir_data.get("blocks", []):
        start_vma = int(b["start_vma"], 0)
        offset = start_vma - MODULE_VMA
        blocks_by_offset[offset] = b

    lines: List[str] = [
        "! ==============================================================================",
        f"! The Story of Thor 2 (Saturn) — {MODULE_NAME} Lossless Assembly Container",
        "! Revision: thor2_ntsc_patched_fe11d2fb",
        f"! Base VMA: 0x{MODULE_VMA:08X} | Size: {MODULE_SIZE} bytes (0x{MODULE_SIZE:05X})",
        "! Toolchain target: GNU assembler (binutils-sh-elf 2.40+2)",
        "! Mechanically generated by tools/asm/generate_full_module_asm.py",
        "! DO NOT COMMIT THIS FILE (Contains full commercial binary payload)",
        "! ==============================================================================",
        "",
        '    .section .text, "ax"',
        "    .global _start",
        "    .global entry_06004000",
        "    .global bb_06004000",
        "    .global bb_06004280",
    ]

    for lbl in ir_data.get("labels", []):
        lines.append(f"    .global {lbl['name']}")

    lines.extend([
        "",
        "_start:",
        "entry_06004000:",
    ])

    offset = 0
    total_len = len(module_bytes)

    while offset < total_len:
        # 1. Emit any labels at current offset
        if offset in labels_by_offset:
            for lbl in labels_by_offset[offset]:
                # avoid duplicating _start/entry_06004000
                if lbl not in ("_start", "entry_06004000"):
                    lines.append(f"{lbl}:")

        # 2. Check if proven code starts here
        if offset in blocks_by_offset:
            blk = blocks_by_offset[offset]
            blk_id = blk["block_id"]
            lines.append(f"! --- CONFIRMED_CODE: {blk_id} (VMA 0x{MODULE_VMA + offset:08X}) ---")
            for insn in blk["instructions"]:
                lines.append(f"    {insn['asm_line']:<32} ! {insn['comment']}")
            offset += blk["byte_length"]
            continue

        # 3. Emit RAW_UNKNOWN byte directives
        # Run until next label, next block, or max 16 bytes
        next_boundary = total_len
        for b_off in blocks_by_offset:
            if b_off > offset and b_off < next_boundary:
                next_boundary = b_off
        for l_off in labels_by_offset:
            if l_off > offset and l_off < next_boundary:
                next_boundary = l_off

        chunk_len = min(16, next_boundary - offset)
        chunk = module_bytes[offset:offset + chunk_len]
        byte_str = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    .byte   {byte_str}")
        offset += chunk_len

    lines.append("")
    lines.append("    .global _end_0TH2")
    lines.append("_end_0TH2:")
    lines.append("")

    with open(out_s_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"Generated Assembly: {out_s_path} ({len(lines)} lines)")


def generate_linker_script(ir_data: Dict[str, Any], out_ld_path: str) -> None:
    """Generate linker script with address and size assertions."""
    os.makedirs(os.path.dirname(os.path.abspath(out_ld_path)), exist_ok=True)

    assertions: List[str] = [
        f'    ASSERT(ADDR(.text) == 0x{MODULE_VMA:08X}, "VMA of .text must be 0x{MODULE_VMA:08X}")',
        f'    ASSERT(SIZEOF(.text) == {MODULE_SIZE}, "Size of .text must be exactly {MODULE_SIZE} bytes")',
    ]
    for lbl in ir_data.get("labels", []):
        name = lbl["name"]
        vma = lbl["vma"]
        assertions.append(f'    ASSERT({name} == {vma}, "{name} address mismatch")')

    ld_content = f"""/* Linker script for {MODULE_NAME} lossless assembly container */
OUTPUT_FORMAT("elf32-sh")
OUTPUT_ARCH(sh:sh2)
ENTRY(_start)

SECTIONS
{{
    . = 0x{MODULE_VMA:08X};

    .text : {{
        _text_start = .;
        *(.text)
        *(.text.*)
        _text_end = .;
    }}

{chr(10).join(assertions)}

    /DISCARD/ : {{
        *(.comment)
        *(.note.*)
    }}
}}
"""
    with open(out_ld_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(ld_content)
    print(f"Generated Linker Script: {out_ld_path}")


def generate_manifest(ir_data: Dict[str, Any], out_json_path: str) -> None:
    """Generate legal-safe public metadata manifest."""
    os.makedirs(os.path.dirname(os.path.abspath(out_json_path)), exist_ok=True)

    blocks_summary = []
    total_code_bytes = 0
    for b in ir_data.get("blocks", []):
        blen = b["byte_length"]
        total_code_bytes += blen
        blocks_summary.append({
            "block_id": b["block_id"],
            "runtime_start": b["start_vma"],
            "runtime_end": b["end_vma"],
            "byte_length": blen,
            "instruction_count": b["instruction_count"],
        })

    manifest = {
        "module": MODULE_NAME,
        "revision": "thor2_ntsc_patched_fe11d2fb",
        "module_runtime_base": f"0x{MODULE_VMA:08X}",
        "module_size": MODULE_SIZE,
        "confirmed_code_bytes": total_code_bytes,
        "raw_unknown_bytes": MODULE_SIZE - total_code_bytes,
        "code_blocks": blocks_summary,
        "labels": [lbl["name"] for lbl in ir_data.get("labels", [])],
        "expected_output_sha256": CANONICAL_MODULE_SHA,
        "assembler_tool_identity": "GNU assembler (binutils-sh-elf 2.40+2) 2.40",
        "linker_tool_identity": "GNU ld (binutils-sh-elf 2.40+2) 2.40",
        "provenance_identity": "T2-ASM-02",
    }

    with open(out_json_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(manifest, f, indent=2)
    print(f"Generated Manifest: {out_json_path}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate 0TH2.BIN Lossless Assembly Container")
    parser.add_argument("--repo-root", default=None, help="Root repository directory")
    args = parser.parse_args()

    repo_root = args.repo_root or os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

    # Paths
    scratch_module = os.path.join(repo_root, "scratch", "0TH2.BIN")
    ir_path = os.path.join(repo_root, "scratch", "assembly_ir.json")
    out_s_path = os.path.join(repo_root, ".private", "asm", "0TH2", "0TH2.s")
    out_ld_path = os.path.join(repo_root, "asm", "linker", "0TH2.ld")
    out_manifest_path = os.path.join(repo_root, "asm", "manifests", "0TH2.BIN.json")

    print(f"Extracting {MODULE_NAME} from disc...")
    module_bytes = extract_canonical_module(repo_root)
    os.makedirs(os.path.dirname(scratch_module), exist_ok=True)
    with open(scratch_module, "wb") as f:
        f.write(module_bytes)

    print("Running C++ export_sh2_asm_ir to obtain Thor-decoder-backed IR...")
    ir_data = run_cpp_ir_exporter(repo_root, scratch_module, ir_path)

    print(f"Generating private assembly {out_s_path}...")
    generate_assembly(module_bytes, ir_data, out_s_path)

    print(f"Generating linker script {out_ld_path}...")
    generate_linker_script(ir_data, out_ld_path)

    print(f"Generating public manifest {out_manifest_path}...")
    generate_manifest(ir_data, out_manifest_path)

    print("\n=== FULL MODULE ASSEMBLY GENERATION COMPLETE ===")
    return 0


if __name__ == "__main__":
    sys.exit(main())
